#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PHASE_A  1
#define PHASE_B  2
#define PHASE_C  4

#define DEFAULT_FREQUENCY_MIN		49
#define DEFAULT_FREQUENCY_MAX		51

#define FREQUENCY_SENSETIVITY		5
#define FREQUENCY_WATCHDOG_VALUE	10

#endif
